# -*- coding: utf-8 -*-
"""Lab 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tu-TJrwIYTvvLaWeMcGBs8-rK-Qwzz0
"""

TP = 50
FP = 8
TN = 32
FN = 10

total = TP + FP + TN + FN
print("Total Predictions:", total)

accuracy = (TP + TN) / total
print("Accuracy:", accuracy)

precision = TP / (TP + FP)
print("Precision:", precision)

recall = TP / (TP + FN)
print("Recall:", recall)

f1 = 2 * (precision * recall) / (precision + recall)
print("F1 Score:", f1)

SSR = 420
SSE = 180

SST = SSR + SSE
print("SST:", SST)

R2 = SSR / SST
print("R²:", R2)

print("Model explains more than 70% variance:", R2 > 0.7)

errors = [2, 4, 1, 9, 4]

mse = sum(errors) / len(errors)
print("Mean Squared Error:", mse)

ei_sq = 9
MSE = 3
p = 3
hii = 0.2

D = (ei_sq / (p * MSE)) * (hii / ((1 - hii) ** 2))
print("Cook's Distance:", D)

threshold = 4 / 25
print("Threshold:", threshold)

print("Influential Observation:", D > threshold)

# Example format
# y = a + bx

a = 10
b = 2.5
x = 12

y = a + b * x
print("Predicted Value:", y)

# Explanation
print("Intercept: value when rainfall is 0")
print("Slope: change in yield for each unit increase in rainfall")